- name: Install Nginx
  apt:
    name: nginx
    state: latest
  become: yes

- name: Copy Nginx configuration file
  template:
    src: default
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Copy website files to Nginx root directory
  copy:
    src: data.php
    dest: /var/www/html
  become: yes

- name: Restart Nginx Service
  become: yes
  service:
    name: nginx
    state: restarted

- name: Ensure Nginx service is running and enabled
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes