- name: Download MariaDB repository setup script
  get_url:
    url: https://r.mariadb.com/downloads/mariadb_repo_setup
    dest: /tmp/mariadb_repo_setup.sh
    mode: '0755'
  become: yes

- name: Add MariaDB repository
  command: /tmp/mariadb_repo_setup.sh --mariadb-server-version="mariadb-11.3.1"
  args:
    creates: /etc/apt/sources.list.d/mariadb.list
  become: yes

- name: Update apt package cache
  apt:
    update_cache: yes
  become: yes

- name: Install MariaDB 11.3
  apt:
    name: mariadb-server
    state: present
  become: yes

- name: Copy MariaDB configuration file
  copy:
    src: my.cnf
    dest: /etc/mysql/my.cnf
  become: yes

- name: Restart MariaDB service
  service:
    name: mysql
    state: restarted
  become: yes

- name: Change root password
  command: mysqladmin -u root password "{{ db_root_password }}"
  become: yes
  vars:
    db_root_password: "E24h7U5kA9HJhq5VM98pm7p5zmJpf8AK"

- name: Copy database file to server
  copy:
    src: nsapool.sql
    dest: /tmp/nsapool.sql
  become: yes

- name: Create database nsapool
  command: mysql -u root -e "CREATE DATABASE IF NOT EXISTS nsapool;"
  become: yes

- name: Create user nsad04
  command: mysql -u root -e "CREATE USER 'nsad04'@'localhost' IDENTIFIED BY '{{ db_user_password }}';"
  become: yes
  vars:
    db_user_password: "E24h7U5kA9HJhq5VM98pm7p5zmJpf8AK"

- name: Grant all privileges to user nsad04
  command: mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'nsad04'@'localhost';"
  become: yes

- name: Load database into nsapool
  command: mysql -u nsad04 -p{{ db_user_password }} -e "USE nsapool; SOURCE /tmp/nsapool.sql;"
  become: yes
  vars:
    db_user_password: "E24h7U5kA9HJhq5VM98pm7p5zmJpf8AK"