name: Execute technologies.sh and update technologies.md
on:
    push:
        branches:
            - master

jobs:
    run-script:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Run technologies.sh
              run: |
                bash technologies.sh
                git config user.name github-actions
                git config user.email github-actions@github.com

                # Check if there are changes to commit
                if [[ -n "$(git status --porcelain)" ]]; then
                    git add .
                    git commit -m "GitHub Actions - Update technologies.md"
                    git push
                else
                    echo "No changes to commit."
                fi