name: Execute technologies.sh and update technologies.md
on:
    push:
        branches:
            - master

jobs:
    run-script:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Run technologies.sh
              run: |
                  bash technologies.sh
                  git diff --exit-code || (git config --global user.name "GitHub Actions" && git config --global user.email "actions@users.noreply.github.com" && git add technologies.md && git commit -m "Update technologies.md" && git push https://x-access-token:$GH_TOKEN@github.com/AlxisHenry/epitech.git)
