name: Execute technologies.sh on push
on:
    push:
        branches:
            - master

jobs:
    run-script:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Run technologies.sh
              run: bash technologies.sh
